# Generated by Django 5.2.5 on 2025-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('trip', 'Trip'), ('story', 'Story'), ('faq', 'FAQ')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_embedd_object__3d93ab_idx')],
                'unique_together': {('object_type', 'object_id')},
            },
        ),
    ]
