# Generated by Django 5.2.5 on 2025-08-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprecommendation',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.trip'),
        ),
    ]
