# Generated by Django 5.2.5 on 2025-08-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Adjust dependency to point to initial squashed migration since 0002-0009 are consolidated into 0001
    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # This migration's operations are already present in 0001_initial (squashed schema). Make it a no-op.
    operations = []
