# Generated by Django 5.2.5 on 2025-08-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_embedding'),
        ('core', '0011_messagetemplate_booking_advance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # All objects added previously; make this a noop to repair chain.
    operations = []
