# Generated by Django 4.2.24 on 2025-10-31 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_booking_enhancements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon_name", models.CharField(max_length=50)),
                ("points_reward", models.PositiveIntegerField()),
                ("unlock_condition", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.CreateModel(
            name="BadgeUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_id", models.CharField(max_length=50)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Badge Unlocks",
            },
        ),
        migrations.CreateModel(
            name="CampaignAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("occupancy_monitoring", "Occupancy Monitoring"),
                            ("lead_nurturing", "Lead Nurturing"),
                            ("promotional", "Promotional"),
                            ("reengagement", "Re-engagement"),
                        ],
                        default="occupancy_monitoring",
                        max_length=30,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message_body", models.TextField()),
                ("target_leads_count", models.PositiveIntegerField(default=0)),
                ("qualified_leads_count", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("messages_delivered", models.PositiveIntegerField(default=0)),
                ("messages_read", models.PositiveIntegerField(default=0)),
                ("responses_received", models.PositiveIntegerField(default=0)),
                ("bookings_generated", models.PositiveIntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "message_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Campaign Analytics",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLeadTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Message Sent"),
                            ("delivered", "Message Delivered"),
                            ("read", "Message Read"),
                            ("responded", "Responded"),
                            ("converted", "Converted"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("response_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("reward_points", models.PositiveIntegerField()),
                ("icon_name", models.CharField(max_length=50)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("trip_view", "Trip View"),
                            ("trip_bookmark", "Trip Bookmark"),
                            ("booking_started", "Booking Started"),
                            ("booking_completed", "Booking Completed"),
                            ("review_written", "Review Written"),
                            ("trip_shared", "Trip Shared"),
                            ("referral_sent", "Referral Sent"),
                            ("daily_login", "Daily Login"),
                            ("lead_submitted", "Lead Submitted"),
                            ("challenge_completed", "Challenge Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_count", models.PositiveIntegerField(default=1)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Challenges",
                "ordering": ["ends_at"],
            },
        ),
        migrations.CreateModel(
            name="GamificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_id", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("trip_view", "Trip View"),
                            ("trip_bookmark", "Trip Bookmark"),
                            ("booking_started", "Booking Started"),
                            ("booking_completed", "Booking Completed"),
                            ("review_written", "Review Written"),
                            ("trip_shared", "Trip Shared"),
                            ("referral_sent", "Referral Sent"),
                            ("daily_login", "Daily Login"),
                            ("lead_submitted", "Lead Submitted"),
                            ("challenge_completed", "Challenge Completed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("badges_unlocked", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadPrioritizationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                        ],
                        default=4,
                    ),
                ),
                ("queue_position", models.PositiveIntegerField(default=0)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("last_follow_up", models.DateTimeField(blank=True, null=True)),
                ("follow_up_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority_level", "queue_position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadQualificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("engagement", "Engagement Rule"),
                            ("intent", "Intent Rule"),
                            ("fit", "Fit Rule"),
                            ("urgency", "Urgency Rule"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition", models.JSONField()),
                ("points_value", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeadQualificationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_score", models.PositiveSmallIntegerField(default=0)),
                ("intent_score", models.PositiveSmallIntegerField(default=0)),
                ("fit_score", models.PositiveSmallIntegerField(default=0)),
                ("urgency_score", models.PositiveSmallIntegerField(default=0)),
                ("total_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("warm", "Warm"),
                            ("cold", "Cold"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="cold",
                        max_length=20,
                    ),
                ),
                ("last_scored_at", models.DateTimeField(auto_now=True)),
                ("scoring_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                ("otp_code", models.CharField(max_length=6)),
                ("hashed_otp", models.CharField(max_length=128)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Review"),
                            ("auto_scan", "Auto Scan"),
                            ("user_proof", "User Screenshot"),
                            ("bank_api", "Bank API"),
                            ("sms_confirmation", "SMS Confirmation"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Manual Review"),
                            ("verified", "Payment Verified"),
                            ("rejected", "Payment Rejected"),
                            ("auto_verified", "Auto Verified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("proof_document", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("trip_view", "Trip View"),
                            ("booking_completed", "Booking Completed"),
                            ("review_written", "Review Written"),
                            ("trip_shared", "Trip Shared"),
                            ("referral", "Referral Bonus"),
                            ("challenge_completed", "Challenge Completed"),
                            ("manual_award", "Manual Award"),
                            ("manual_deduct", "Manual Deduction"),
                        ],
                        default="manual_award",
                        max_length=50,
                    ),
                ),
                ("from_level", models.PositiveIntegerField()),
                ("to_level", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Point Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("initial_contact", "Initial Contact"),
                            ("follow_up", "Follow Up"),
                            ("abandoned_reengage", "Abandoned Re-engage"),
                        ],
                        db_index=True,
                        default="follow_up",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(default="Follow up", max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("old_value", models.CharField(blank=True, max_length=50)),
                ("new_value", models.CharField(blank=True, max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserChallengeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_progress", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reward_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Challenge Progress",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(db_index=True, default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("total_earned_points", models.PositiveIntegerField(default=0)),
                ("daily_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("total_trip_views", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("completed_challenges", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Progress",
                "ordering": ["-points"],
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="lead",
            name="intent_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contact_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_action_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("engaged", "Engaged"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("advance_paid", "Advance Paid"),
                    ("balance_due", "Balance Due"),
                    ("completed", "Completed"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="payment",
            name="booking_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmation_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmation_whatsapp_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_vpa",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="risk_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="payment",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low Risk"),
                    ("medium", "Medium Risk"),
                    ("high", "High Risk"),
                    ("fraud", "Suspected Fraud"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="risk_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Manual Review"),
                    ("verified", "Payment Verified"),
                    ("rejected", "Payment Rejected"),
                    ("auto_verified", "Auto Verified"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="bookinglimit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("initiated", "Initiated"),
                    ("waiting", "Waiting"),
                    ("verified", "Verified"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="upi_txn_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="core_paymen_created_f77624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "status"], name="core_paymen_booking_9e1c70_idx"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userchallengeprogress",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.challenge"
            ),
        ),
        migrations.AddField(
            model_name="userchallengeprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionaudit",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_trail",
                to="core.payment",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pointtransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentverificationlog",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to="core.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentverificationlog",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["phone_number", "-created_at"],
                name="core_otpver_phone_n_8089a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["expires_at"], name="core_otpver_expires_b4c0c3_idx"
            ),
        ),
        migrations.AddField(
            model_name="leadqualificationscore",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification_score",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="leadprioritizationqueue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="priority_queue_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadprioritizationqueue",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority_queue",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="gamificationevent",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="gamificationevent",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.trip",
            ),
        ),
        migrations.AddField(
            model_name="gamificationevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamification_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignleadtracking",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_tracking",
                to="core.campaignanalytics",
            ),
        ),
        migrations.AddField(
            model_name="campaignleadtracking",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_tracking",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="campaignanalytics",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.messagetemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaignanalytics",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="core.trip",
            ),
        ),
        migrations.AddField(
            model_name="badgeunlock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_unlocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["-points"], name="core_userpr_points_8c4b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(fields=["level"], name="core_userpr_level_9fa61c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userchallengeprogress",
            unique_together={("user", "challenge")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "due_at"], name="core_task_status_4aa924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["lead", "status"], name="core_task_lead_id_63fe6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamificationevent",
            index=models.Index(
                fields=["user", "-created_at"], name="core_gamifi_user_id_ab6d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamificationevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="core_gamifi_event_t_560244_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignleadtracking",
            unique_together={("campaign", "lead")},
        ),
        migrations.AlterUniqueTogether(
            name="badgeunlock",
            unique_together={("user", "badge_id")},
        ),
    ]
